<a href="https://colab.research.google.com/github/HarshChaudhary29/ML-Zoomcamp/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Creating Arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
arr[2]

3

In [11]:
arr[4] = 6

In [12]:
arr

array([1, 2, 3, 4, 6])

In [13]:
np.arange(2,10,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [14]:
type(arr)

numpy.ndarray

In [15]:
np.linspace(2,3,11)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ])

#Multi-Dimensional Arrays

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.full((5,2),3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [18]:
a = np.array([[1,2],[3,4]])

In [19]:
a[1,0]

3

In [21]:
a[1]

array([3, 4])

In [22]:
a[:,1]

array([2, 4])

In [24]:
a[:,1] = [1,2]

In [25]:
a

array([[1, 1],
       [3, 2]])

#Random Array

In [28]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
np.random.randint(low = 0, high = 100 , size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

#Element-Wise Operations

In [36]:
a = np.arange(2,5)

In [34]:
a

array([2, 3, 4])

In [35]:
a*2

array([4, 6, 8])

In [37]:
a+1

array([3, 4, 5])

#Comaprison Operations

In [53]:
a

array([2, 3, 4])

In [54]:
a>=2

array([ True,  True,  True])

In [61]:
b = np.random.randint(low = 2, high = 10, size = (3))

In [62]:
b

array([5, 5, 9])

In [64]:
a[a < b]

array([2, 3, 4])